version: "3.9"

services:
  prometheus:
    container_name: ai-workflow-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - asi
    restart: unless-stopped

  grafana:
    container_name: ai-workflow-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - asi
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest # ← используй latest, чтобы точно была свежая версия
    # command: n8n start:contentReference[oaicite:1]{index=1}
    environment:
      # - WEBHOOK_TUNNEL_URL=https://indefinable-unpanelled-ute.ngrok-free.dev/
      - WEBHOOK_URL=https://indefinable-unpanelled-ute.ngrok-free.dev
    # - N8N_HOST=indefinable-unpanelled-ute.ngrok-free.dev
    # - N8N_PROTOCOL=https
    # - N8N_PORT=443
    ports:
      - "5678:5678"
    env_file:
      - .env.example
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - asi

  code-reviewer-agent:
    build: ./code-reviewer-agent
    container_name: code-reviewer-agent
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    env_file:
      - ./code-reviewer-agent/.env
    networks:
      - asi

networks:
  asi:
    name: asi
    external: true

volumes:
  n8n_data:
